### ISSUE TITLE
[TASK] Configure CI pipeline and SonarQube for comprehensive testing and code quality

### ISSUE THREAD

**Issue by Sylvie-Molinatto** [polito-ThesisManagement/Portale-PoliTO#48]
## Task Description
- Integrate code coverage support for back-end unit and integration tests within the CI pipeline.
- Enable code coverage reporting for Cypress E2E tests as part of the front-end testing.
- Configure SonarQube properties in sonar-project.properties for accurate code quality analysis.
- Update the CI pipeline to run both front-end and back-end tests, followed by a SonarQube analysis to collect overall test coverage and code quality metrics.

## Linked User Story (-ies)
- This task is not directly linked to a specific user story.

## Notes (optional)
- Ensure compatibility between CI pipelines and SonarQube for both local development and production environments.

**Comment by therossee** [comment]
If you need help, tell me
