### ISSUE TITLE
[TASK] Populate db with existing data

### ISSUE THREAD

**Issue by lucabubi** [polito-ThesisManagement/Portale-PoliTO#58]
## Task Description
- Populate the thesis proposals table with existing proposals by adding at least 100 proposals with the corresponsing translations.
- Populate the students table with dummy students' data in order to showcase a larger variety of the portal functionalities.
- Populate the teachers table with existing teacher's data.
- Populate the degree table.

## Linked User Story (-ies)
- #1

**Comment by Sylvie-Molinatto** [comment]
The db has been partially populated but many thesis proposals still needs to be added.
In order to have some proposals for the interfaces implementation the branch has been merged into main but the task is not done and will be concluded successively.
